### ISSUE TITLE
PP counter does'nt work

### ISSUE THREAD

**Issue by Bibou1494** [l3lackShark/gosumemory#196]
hello I install your software but since the PP counter stays on 0 and does not change in game but display the max that can be had when selecting beatmap

**Comment by Jxcky120** [comment]
Download the updated version: https://github.com/l3lackShark/gosumemory/actions/runs/4573585206 . Scroll down to the artifact and then click on the desired download.

**Comment by Bibou1494** [comment]
and now what i need to do ?

**Comment by Jxcky120** [comment]
Extract it and then run gosumemory.exe. Note: If you want a ingame overlay, you need to set it to true in the config.ini

**Comment by YuvalM836** [comment]
> Download the updated version: https://github.com/l3lackShark/gosumemory/actions/runs/4573585206 . Scroll down to the artifact and then click on the desired download.

This seems to not work anymore.
This update only fixed the 100's, 50's and miss counters. (In my experience)
The PP counter, expected PP counter, and current rank aren't showing.

![image](https://github.com/l3lackShark/gosumemory/assets/74706791/c5608d41-6711-4b2b-bc30-9cd5824adca4)


**However**,  channels on YouTube and streamers still use gosumemory without issues, meaning there is a way to fix this.
Is there any way to fix this on my own? 
(Without waiting for the next update.)

**Comment by Jxcky120** [comment]
It seems to work for me fine. So I have no clue to be honest... I would like to ask if there are any errors (other than mp3 not found etc.)

**Comment by Jxcky120** [comment]
Also, I think it may be because you're playing other modes than osu!standard. So I am not sure if the pp counter works.

**Comment by YuvalM836** [comment]
> It seems to work for me fine. So I have no clue to be honest... I would like to ask if there are any errors (other than mp3 not found etc.)

I play standard.

I do have errors though (other than mp3 not found):
1. 2023/05/27 20:42:22 Binary update failed: Get "https://api.github.com/repos/l3lackShark/gosumemory/releases": dial tcp 140.82.121.5:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.
2. fopen: No such file or directory

The fopen error (error 2) is printed every time I switch a song, and whenever I play a map. Seems to have no effect.
It seems like the socket error might be caused by my antivirus, I'm looking into it now. Can't really find the cause, I added gosumemory and programs accesed by it to the exceptions.

I'll update if I find the problem.
Thanks anyways :)
