### ISSUE TITLE
Failed to inject into osu's process https://omk.pics/12/wVugx

### ISSUE THREAD

**Issue by moth-os** [l3lackShark/gosumemory#231]
![hell](https://github.com/l3lackShark/gosumemory/assets/172361976/29debfc1-b1fa-4e21-8ad1-30ded10af57b)

I've already tried disabling my antivirus and running it as administrator, as well as uninstalling/reinstalling (multiple times) but nothing has worked. I saw on another post that I could manually download the "https://omk.pics/12/wVugx", but trying to visit it just gives a "Secure Connection Failed" with the error code being PR_CONNECT_RESET_ERROR

**Comment by omkelderman** [comment]
I do not know the inner workings of how the gameoverlay stuff works, so unfortunately I cannot help with the first part of your question, however that omk.pics url is mine as blackshark uses my file host, so that is the only bit I can comment on here: That download is hosted on cloudflare's CDN, so it might be that you have trouble reaching cloudflare servers for some reason. It works just fine for me.

What do you see when you go to https://omk.pics/cdn-cgi/trace? Does it give the same error?

**Comment by moth-os** [comment]
That link gives me the same error. Though I was able to get the gameplay overlay I was planning on using to work in a different application instead ([tosu](https://github.com/KotRikD/tosu)). Should I just mark this as solved? Also thank you for the reply.

**Comment by omkelderman** [comment]
ye if that link also does not work then there is something weird going on with the connection between you and cloudflare. I have no idea why and unfortunately I cannot help you.
Glad to hear to got it working with tosu, thats great.

And yes, I'll mark this as closed as connection issues with cloudflare is not something we can do anything about
